### ISSUE TITLE
"ReferenceError: window is not defined" with Server-Side Rendering

### ISSUE THREAD

**Issue by leopoldjoy** [jstejada/react-typist#11]
Hello,

My `React` is pre-rendered on the server, and when I try to use `react-typist` I get this error on the server:

    ReferenceError: window is not defined
    [1]     at new Typist (/Users/user/myapp/node_modules/react-typist/dist/Typist.js:146:41)
    [1]     at ReactCompositeComponentMixin.mountComponent (/Users/user/myapp/node_modules/react/lib/ReactCompositeComponent.js:148:18)
    [1]     at wrapper [as mountComponent] (/Users/user/myapp/node_modules/react/lib/ReactPerf.js:66:21)
    [1]     at Object.ReactReconciler.mountComponent (/Users/user/myapp/node_modules/react/lib/ReactReconciler.js:37:35)
    [1]     at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/user/myapp/node_modules/react/lib/ReactMultiChild.js:241:44)
    [1]     at ReactDOMComponent.Mixin._createContentMarkup (/Users/user/myapp/node_modules/react/lib/ReactDOMComponent.js:591:32)
    [1]     at ReactDOMComponent.Mixin.mountComponent (/Users/user/myapp/node_modules/react/lib/ReactDOMComponent.js:479:29)
    [1]     at Object.ReactReconciler.mountComponent (/Users/user/myapp/node_modules/react/lib/ReactReconciler.js:37:35)
    [1]     at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/user/myapp/node_modules/react/lib/ReactMultiChild.js:241:44)
    [1]     at ReactDOMComponent.Mixin._createContentMarkup (/Users/user/myapp/node_modules/react/lib/ReactDOMComponent.js:591:32)

Any idea what I can do to avoid this issue?

**Comment by leopoldjoy** [comment]
Created a fix: https://github.com/jstejada/react-typist/pull/12
