### ISSUE TITLE
Error in starting

### ISSUE THREAD

**Issue by albertoziveri** [jstejada/react-typist#61]
Hello,
the plugin seems to not be property configured when building.
See the error. After installing all the dependencies with npm install, then building and doing npm start it gives the following:
`ERROR in ./examples/main.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/albertoziveri/Downloads/react-typist-master/node_modules/sass-loader/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
 @ ./examples/index.js 17:0-22

ERROR in ./src/Cursor.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/albertoziveri/Downloads/react-typist-master/node_modules/sass-loader/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
 @ ./src/Cursor.jsx 17:0-24
Child extract-text-webpack-plugin:
    
    ERROR in Cannot find module 'node-sass'
Child extract-text-webpack-plugin:
    
    ERROR in Cannot find module 'node-sass'
webpack: Failed to compile.

`

**Comment by Jakuska** [comment]
I had the same error. I tried to reinstall the package but it still didn't work.  So I deleted node-sass from package.json and reinstalled it again. I had to do that because otherwise it would install version 3 instead of version 4. Anyway, version 4 works for me. Oh and I also had to change double quotes to single quote in utils.js (I saw this error in the terminal). Hope that helps!
